pyinstaller --onefile src/main.py \
    --name simple-timer \
    --exclude-module gi\
    --exclude-module pygame.camera \
    --exclude-module pygame.fastevent \
    --exclude-module pygame.gfxdraw \
    --exclude-module pygame.image \
    --exclude-module pygame.joystick \
    --exclude-module pygame.scrap \
    --exclude-module pygame.surfarray \
    --exclude-module pygame.sprite \
    --exclude-module pygame.transform \
    --exclude-module pygame.libs \
    --exclude-module pygame.movie \
    --exclude-module pygame.midi \
    --exclude-module pygame._sdl2 \
    --exclude-module pygame.display \
    --exclude-module pygame.freetype \
    --hidden-import=optparse